=== MerProjects/NSDMS-Eclipse/MerSETA/src/main/webapp/xsd/qualification.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
  <xsd:element name="SAQAQUALIFICATIONS">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element maxOccurs="unbounded" name="QUALIFICATION">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="DOWNLOAD_DATE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="LAST_UPDATE_DATE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="QUALIFICATION_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="QUALIFICATION_TITLE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="150"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="SGB_NAME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="50"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="FIELD" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="71"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="PROVIDER_CODE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="PROVIDER_NAME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="70"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="PROVIDER_ETQA_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="ETQA_ACRONYM" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="35"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="ETQA_NAME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="150"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="QUALIFICATION_TYPE_DESC" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="30"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="FIELD_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="60"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="SUBFIELD_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="80"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="ABET_BAND_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="QUALIFICATION_MINIMUM_CREDITS" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="NQF_LEVEL_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="NQF_LEVEL_G2_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"> <xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="27"/> </xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUALIFICATION_CLASS_DESC" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="QUALIFICATION_PURPOSE" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUAL_LEARNING_ASSUMED_IN_PLACE" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="RECOGNIZE_PREV_LEARNING_FLAG" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="1"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="QUAL_RULES_OF_COMBINATION" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="ELOAC_QUALIFICATION_OUTCOME" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="ELOAC_QUAL_ASSESSMENT_CRITERIA" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUAL_INTL_BENCHMARKING_MEMO" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUAL_ARTICULATION_OPTIONS" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUAL_MODERATION_OPTIONS" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUAL_ASSESSOR_CRITERIA" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="QUALIFICATION_NOTES" minOccurs="0" od:jetType="memo" od:sqlSType="text"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="536870910"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="REGISTRATION_STATUS_DESC" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="59"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="SAQA_DECISION_NUMBER" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="20"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="QUAL_REGISTRATION_START_DATE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="QUAL_REGISTRATION_END_DATE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="TRANSITION_PERIOD" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="LAST_DATE_FOR_ENROLMENT" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="TRAIN_OUT_PERIOD" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="LAST_DATE_FOR_ACHIEVEMENT" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="IS_LEARNING_PROGRAMME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="4"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="LEARNING_PROGRAMME_QUAL" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
	    </xsd:sequence>
	  </xsd:complexType>
	</xsd:element>
        <xsd:element minOccurs="0" maxOccurs="unbounded" name="US_QUALIFICATION_LINK">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="QUALIFICATION_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="US_QUAL_TYPE_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="UNIT_STD_TITLE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="200"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="UNIT_STANDARD_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="NQF_LEVEL_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="NQF_LEVEL_G2_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="27"/></xsd:restriction></xsd:simpleType></xsd:element>
              <xsd:element name="UNIT_STD_NUMBER_OF_CREDITS" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
            </xsd:sequence>
           </xsd:complexType>
        </xsd:element>
        <xsd:element minOccurs="0" maxOccurs="unbounded" name="LP_QUALIFICATION_LINK">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="QUALIFICATION_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="LP_QUALIFICATION_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="LP_QUALIFICATION_TITLE" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="150"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="LP_PROVIDER_NAME" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="70"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="LP_NQF_LEVEL_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element> 
			  <xsd:element name="LP_NQF_LEVEL_G2_DESCRIPTION" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="26"/></xsd:restriction></xsd:simpleType></xsd:element> 
              <xsd:element name="LP_QUAL_MINIMUM_CREDITS" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int" />
              <xsd:element name="LP_QUAL_REGISTRATION_END_DATE" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime" />
              <xsd:element name="LP_ETQA_ACRONYM" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar"><xsd:simpleType><xsd:restriction base="xsd:string"><xsd:maxLength value="50"/></xsd:restriction></xsd:simpleType></xsd:element> 
            </xsd:sequence>
           </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
     </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== MerProjects/NSDMS-Eclipse/MerSETA/src/main/webapp/xsd/qualification1.xml
<?xml version="1.0" encoding="UTF-8"?>
<SAQAQUALIFICATIONS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="qualification.xsd">
  <QUALIFICATION>
    <DOWNLOAD_DATE>2001-12-31T12:00:00</DOWNLOAD_DATE>
    <LAST_UPDATE_DATE>2001-12-31T12:00:00</LAST_UPDATE_DATE>
    <QUALIFICATION_ID>0</QUALIFICATION_ID>
    <QUALIFICATION_TITLE>QUALIFICATION_TITLE</QUALIFICATION_TITLE>
    <SGB_NAME>SGB_NAME</SGB_NAME>
    <FIELD>FIELD</FIELD>
    <PROVIDER_CODE>PROVIDER_CODE</PROVIDER_CODE>
    <PROVIDER_NAME>PROVIDER_NAME</PROVIDER_NAME>
    <PROVIDER_ETQA_ID>0</PROVIDER_ETQA_ID>
    <ETQA_ACRONYM>ETQA_ACRONYM</ETQA_ACRONYM>
    <ETQA_NAME>ETQA_NAME</ETQA_NAME>
    <QUALIFICATION_TYPE_DESC>QUALIFICATION_TYPE_DESC</QUALIFICATION_TYPE_DESC>
    <FIELD_DESCRIPTION>FIELD_DESCRIPTION</FIELD_DESCRIPTION>
    <SUBFIELD_DESCRIPTION>SUBFIELD_DESCRIPTION</SUBFIELD_DESCRIPTION>
    <ABET_BAND_DESCRIPTION>ABET_BAND_DESCRIPTION</ABET_BAND_DESCRIPTION>
    <QUALIFICATION_MINIMUM_CREDITS>0</QUALIFICATION_MINIMUM_CREDITS>
    <NQF_LEVEL_DESCRIPTION>NQF_LEVEL_DESCRIPTION</NQF_LEVEL_DESCRIPTION>
    <NQF_LEVEL_G2_DESCRIPTION>NQF_LEVEL_G2_DESCRIPTION</NQF_LEVEL_G2_DESCRIPTION>
    <QUALIFICATION_CLASS_DESC>QUALIFICATION_CLASS_DESC</QUALIFICATION_CLASS_DESC>
    <QUALIFICATION_PURPOSE>QUALIFICATION_PURPOSE</QUALIFICATION_PURPOSE>
    <QUAL_LEARNING_ASSUMED_IN_PLACE>QUAL_LEARNING_ASSUMED_IN_PLACE</QUAL_LEARNING_ASSUMED_IN_PLACE>
    <RECOGNIZE_PREV_LEARNING_FLAG>RECOGNIZE_PREV_LEARNING_FLAG</RECOGNIZE_PREV_LEARNING_FLAG>
    <QUAL_RULES_OF_COMBINATION>QUAL_RULES_OF_COMBINATION</QUAL_RULES_OF_COMBINATION>
    <ELOAC_QUALIFICATION_OUTCOME>ELOAC_QUALIFICATION_OUTCOME</ELOAC_QUALIFICATION_OUTCOME>
    <ELOAC_QUAL_ASSESSMENT_CRITERIA>ELOAC_QUAL_ASSESSMENT_CRITERIA</ELOAC_QUAL_ASSESSMENT_CRITERIA>
    <QUAL_INTL_BENCHMARKING_MEMO>QUAL_INTL_BENCHMARKING_MEMO</QUAL_INTL_BENCHMARKING_MEMO>
    <QUAL_ARTICULATION_OPTIONS>QUAL_ARTICULATION_OPTIONS</QUAL_ARTICULATION_OPTIONS>
    <QUAL_MODERATION_OPTIONS>QUAL_MODERATION_OPTIONS</QUAL_MODERATION_OPTIONS>
    <QUAL_ASSESSOR_CRITERIA>QUAL_ASSESSOR_CRITERIA</QUAL_ASSESSOR_CRITERIA>
    <QUALIFICATION_NOTES>QUALIFICATION_NOTES</QUALIFICATION_NOTES>
    <REGISTRATION_STATUS_DESC>REGISTRATION_STATUS_DESC</REGISTRATION_STATUS_DESC>
    <SAQA_DECISION_NUMBER>SAQA_DECISION_NUMBER</SAQA_DECISION_NUMBER>
    <QUAL_REGISTRATION_START_DATE>2001-12-31T12:00:00</QUAL_REGISTRATION_START_DATE>
    <QUAL_REGISTRATION_END_DATE>2001-12-31T12:00:00</QUAL_REGISTRATION_END_DATE>
    <TRANSITION_PERIOD>0</TRANSITION_PERIOD>
    <LAST_DATE_FOR_ENROLMENT>2001-12-31T12:00:00</LAST_DATE_FOR_ENROLMENT>
    <TRAIN_OUT_PERIOD>0</TRAIN_OUT_PERIOD>
    <LAST_DATE_FOR_ACHIEVEMENT>2001-12-31T12:00:00</LAST_DATE_FOR_ACHIEVEMENT>
    <IS_LEARNING_PROGRAMME>IS_LEARNING_PROGRAMME</IS_LEARNING_PROGRAMME>
    <LEARNING_PROGRAMME_QUAL>0</LEARNING_PROGRAMME_QUAL>
  </QUALIFICATION>
  <US_QUALIFICATION_LINK>
    <QUALIFICATION_ID>0</QUALIFICATION_ID>
    <US_QUAL_TYPE_DESCRIPTION>US_QUAL_TYPE_DESCRIPTION</US_QUAL_TYPE_DESCRIPTION>
    <UNIT_STD_TITLE>UNIT_STD_TITLE</UNIT_STD_TITLE>
    <UNIT_STANDARD_ID>0</UNIT_STANDARD_ID>
    <NQF_LEVEL_DESCRIPTION>NQF_LEVEL_DESCRIPTION</NQF_LEVEL_DESCRIPTION>
    <NQF_LEVEL_G2_DESCRIPTION>NQF_LEVEL_G2_DESCRIPTION</NQF_LEVEL_G2_DESCRIPTION>
    <UNIT_STD_NUMBER_OF_CREDITS>0</UNIT_STD_NUMBER_OF_CREDITS>
  </US_QUALIFICATION_LINK>
  <LP_QUALIFICATION_LINK>
    <QUALIFICATION_ID>0</QUALIFICATION_ID>
    <LP_QUALIFICATION_ID>0</LP_QUALIFICATION_ID>
    <LP_QUALIFICATION_TITLE>LP_QUALIFICATION_TITLE</LP_QUALIFICATION_TITLE>
    <LP_PROVIDER_NAME>LP_PROVIDER_NAME</LP_PROVIDER_NAME>
    <LP_NQF_LEVEL_DESCRIPTION>LP_NQF_LEVEL_DESCRIPTION</LP_NQF_LEVEL_DESCRIPTION>
    <LP_NQF_LEVEL_G2_DESCRIPTION>LP_NQF_LEVEL_G2_DESCRIPTION</LP_NQF_LEVEL_G2_DESCRIPTION>
    <LP_QUAL_MINIMUM_CREDITS>0</LP_QUAL_MINIMUM_CREDITS>
    <LP_QUAL_REGISTRATION_END_DATE>2001-12-31T12:00:00</LP_QUAL_REGISTRATION_END_DATE>
    <LP_ETQA_ACRONYM>LP_ETQA_ACRONYM</LP_ETQA_ACRONYM>
  </LP_QUALIFICATION_LINK>
</SAQAQUALIFICATIONS>
